//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.12 at 07:29:13 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xml.netbeans.org/schema/difficult-for-product", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.metalworld.config.difficult_mapping;
