//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 09:24:24 PM ICT 
//


package com.metalworld.config.coefficient;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.metalworld.config.coefficient package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Coefficient_QNAME = new QName("http://xml.netbeans.org/schema/coefficient", "coefficient");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.metalworld.config.coefficient
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Coefficient }
     * 
     */
    public Coefficient createCoefficient() {
        return new Coefficient();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Coefficient }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.netbeans.org/schema/coefficient", name = "coefficient")
    public JAXBElement<Coefficient> createCoefficient(Coefficient value) {
        return new JAXBElement<Coefficient>(_Coefficient_QNAME, Coefficient.class, null, value);
    }

}
