//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.12 at 10:29:54 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.guitarpark.com/schema/estimation-for-product", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.metalworld.config.product;
